Fix crash on object interaction with purple quest ground marker
DelvUI/DelvUI pull request #166
Opened 2021-08-31 22:44 UTC by arejensen

Interaction with quest item on purple ground marker objective would lead to null being passed to DrawOutlinedText and a memory access violation.

Now passes empty string if argument is null.

2021-08-31 23:17 UTC, jdsmith2816 commented on DelvUI/Interface/HudWindow.cs
> +                    castText ??= "",
Should just be `castText ?? ""` no assignment required, right?

2021-08-31 23:18 UTC, jdsmith2816 requested changes
Should just be castText ?? "" no assignment required, right?

In either case I think that the better solution would be to fix this in `DrawOutlinedText` instead

2021-08-31 23:18 UTC, Kanubiz commented
I would decline this for now since we need the crashes to properly map the IDS

2021-09-01 00:15 UTC, arejensen commented
> Should just be `castText ?? ""` no assignment required, right?

You are absolutely right. 
 
> In either case I think that the better solution would be to fix this in `DrawOutlinedText` instead

I've added a temporary fix in `DrawOutlinedText` until we can figure out the issue with id mapping.

2021-09-01 08:11 UTC, jdsmith2816 commented
Your fix sounds plausible but the `DrawOutlinedText` method should still not crash on null text.  We need that fixed in either case.

2021-09-01 08:15 UTC, Zeffuro commented
> Your fix sounds plausible but the `DrawOutlinedText` method should still not crash on null text. We need that fixed in either case.

Yes sanitycheck still needs to be there, agreed.

2021-09-01 14:42 UTC, arejensen commented
I've submitted #182 which incorporates a check on actor type as outlined by Zeffuro.

2021-09-01 23:14 UTC, closed without merging