Dancer Proc Bar
DelvUI/DelvUI pull request #175
Opened 2021-09-01 06:51 UTC by chipget

This pull request adds bars for the single target DNC procs (Flourishing Cascade and Flourishing Fountain), which default to the color of their corresponding step transformation (i.e., the color of Flourishing Cascade defaults to that of Jete, Flourishing Fountain to Pirouette). The bars default to the size of the feather bars, use the same padding as the feather bars, and default to a location just above those feather bars.

2021-09-01 07:11 UTC, chipget commented
![dnc_image](https://user-images.githubusercontent.com/78664459/131628038-4adc161b-c339-4048-9464-70d4e4a02baa.png)

2021-09-01 22:48 UTC, Bedo9041 requested changes
This appears to be missing Rising Windmill and Bloodshower procs. Ideally they would also be included in the proc bar.
Also this is potentially personal preference, but I'm not a fan of having multiple timer bars on the horizontal bar without them being symmetrical - but I don't think there's a good way to do this for four different procs without significantly cluttering the UI using multiple bars.

2021-09-01 23:04 UTC, Bedo9041 commented
I wouldn't worry about the difference between AoE and ST procs, AoE procs are still used in ST fights over the standard 1-2 combo. And you still get the procs because of flourish.
Maybe have timers be an option, turned off by default - that way if people want the timers (which are useful for deciding between saber dance and using a proc if your getting a ton of esprit in a burst window) they can turn them on.

2021-09-01 23:51 UTC, chipget commented
Okay, this branch now includes your suggestions. The following images show the updated bars. The first corresponds to the fixed bar option, and the final one corresponds to the timer bar option.

![dnc_cascade_fixed](https://user-images.githubusercontent.com/78664459/131759905-ea4404c3-2606-49d0-91c3-a72a309eeb31.png)

![dnc_fountain_fixed](https://user-images.githubusercontent.com/78664459/131759907-ef1f7a6f-8c8f-451b-a2b5-22672a261c9e.png)

![dnc_procs_timers](https://user-images.githubusercontent.com/78664459/131759910-e30bd30e-8d98-4bff-8a4b-736882bd4aab.png)

![dnc_shower_fixed](https://user-images.githubusercontent.com/78664459/131759912-7c92acf2-5362-4896-b121-5d16a4834805.png)

![dnc_windmill_fixed](https://user-images.githubusercontent.com/78664459/131759913-7fa7d6fd-956d-4cc7-b7fd-af406992757b.png)

2021-09-02 00:01 UTC, Bedo9041 approved these changes

2021-09-02 00:22 UTC, merged