PoC: Only Show When Active-options
DelvUI/DelvUI pull request #475
Opened 2021-09-22 22:35 UTC by vond82

Just a quick PoC to show an idea I had to implement on all job packs for stuff that isn't a "main resource", thus why it's not used for Kenki in this case. It would allow for UIs that are a lot less cluttered with empty bars when out of combat especially while being able to pick and choose what you'd like to see.

https://youtu.be/Z5u2DDV3ER8 to showcase why I think this is a lot better personally

2021-09-22 23:49 UTC, vond82 commented
Just wanting to know if this is something others would like for all jobs or if i should scrap the idea

2021-09-22 23:50 UTC, h4cky commented on DelvUI/Interface/Jobs/SamuraiHud.cs
> +        [DragFloat2("Kenki Bar Size" + "##Kenki", max = 2000f)]
For me that, appending "##Kenki", would make sense if there was multiple fields named "Kenki Bar Size" and CategoryField.ID == null (which sadly currently is for the cases which i checked, dynamicList, DragFloat2).

If CategoryField.ID != null the only points when appending ImGui comment to the friendlyName is when you have multiple fields on the same level with the same name.

2021-09-23 00:03 UTC, h4cky commented on DelvUI/Interface/Jobs/SamuraiHud.cs
> +        [DragFloat2("Kenki Bar Size" + "##Kenki", max = 2000f)]
ooooff  i feel that explained it poorly. but basically:
if the friendlyName is "Kenki Bar Size", there is no point to append "##Kenki".
if the firendlyName is "Size", there you have a reason to append "##Kenki" to the name due to IDText() being null for for fields who are not in NestedConfig.

2021-09-23 02:07 UTC, vond82 commented
https://trello.com/c/DNR4ImdD/187-only-show-when-active

2021-09-23 02:08 UTC, vond82 commented
#475

2021-09-23 02:10 UTC, vond82 commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Only Show When Active"](https://trello.com/c/DNR4ImdD/187-only-show-when-active)

2021-09-23 08:47 UTC, jdsmith2816 requested changes
Let's delay this until a beta2 patch release or beta3 and just catch them all at once.

2021-09-23 10:18 UTC, vond82 commented
> Let's delay this until a beta2 patch release or beta3 and just catch them all at once.

Yeah that works, will just work on it slowly til then and hopefully we won't make it too hard to merge down the line

2021-09-26 18:17 UTC, closed without merging

2021-09-26 18:21 UTC, jdsmith2816 commented
@vond82 github autoclosed these PRs when I merged beta2;  please reopen these changes to beta3 branch with any relevant updates and we can get them merged in