Fix DNC proc bar lag
DelvUI/DelvUI pull request #482
Opened 2021-09-23 15:54 UTC by zotlann

Modeled the dnc proc bar after the samurai DrawSenResourceBar to reduce lag.

2021-09-23 20:46 UTC, vond82 commented
I tried this out (tho since I'm on APIv4 I had to change some things) and there is still a delay and I can't really say if it's better or not.  I tried by having the skills that light up next to the procbar just to see the difference in when they'd light up on both builds. It's *definitely* not worse however.

One big benefit of the code in this PR compared to the current version is that it seems to once and for all fix the issues with scaling of the procbar. Thumbs up from me at least :)

2021-09-23 20:51 UTC, vond82 requested changes

2021-09-23 20:51 UTC, vond82 commented on DelvUI/Interface/Jobs/DancerHud.cs
> +                    var builder = BarBuilder.Create(cursorPos, procBarSize).
Just insert .SetBackgroundColor(EmptyColor.Base) on the builder variables so it doesn't look out of place and I'd be happy with all of this, see my other comment

2021-09-26 18:17 UTC, closed without merging

2021-09-26 18:21 UTC, jdsmith2816 commented
@zotlann github autoclosed these PRs when I merged beta2;  please reopen these changes to beta3 branch with any relevant updates and we can get them merged in